/**
 * Mountain terrain — walkable paths, cliff edges, open-world perimeter massifs.
 * MIT / Harvard landscape + international AAA & indie production refs.
 */
import type { ResearchEntry } from "./research-catalog.js";

const T = "mountain_terrain";

export const MOUNTAIN_TERRAIN_PAPERS: ResearchEntry[] = [
  {
    lab: "MIT CSAIL",
    title: "Learning to Generate Terrains with Reinforcement Learning",
    year: 2025,
    venue: "MIT Publications",
    url: "https://www.csail.mit.edu/research/learning-generate-terrains-reinforcement-learning",
    topics: `${T}, procedural mountains, RL terrain synthesis, walkable slope constraints`,
    provenInProduction: false,
  },
  {
    lab: "Harvard Graduate School of Design",
    title: "Terrain Modeling for Landscape Architecture",
    year: 2026,
    venue: "GSD Research",
    url: "https://research.gsd.harvard.edu/",
    topics: `${T}, landform design, ridge-valley grammar, pedestrian circulation on slopes`,
    provenInProduction: false,
  },
  {
    lab: "ETH Zurich",
    title: "Procedural Modeling of Mountains and Glacial Landforms",
    year: 2025,
    venue: "ETH Computer Graphics",
    url: "https://cgl.ethz.ch/research/",
    topics: `${T}, erosion synthesis, ridged multifractal, cliff faces, open world tiling`,
    provenInProduction: true,
  },
  {
    lab: "Guerrilla Games",
    title: "Horizon Zero Dawn — Terrain and Mountain Streaming",
    year: 2023,
    venue: "Guerrilla Games Read",
    url: "https://www.guerrilla-games.com/read/Streaming-the-World-of-Horizon-Zero-Dawn",
    topics: `${T}, AAA perimeter mountains, play disk vs wilderness ring, trail corridors`,
    provenInProduction: true,
  },
  {
    lab: "Ubisoft La Forge",
    title: "Large-Scale Terrain Authoring in Open Worlds",
    year: 2025,
    venue: "Ubisoft La Forge",
    url: "https://www.ubisoft.com/en-us/studio/laforge/publications",
    topics: `${T}, cliff meshes, fall edges, hiking paths, Houdini heightfields`,
    provenInProduction: true,
  },
  {
    lab: "CD Projekt RED",
    title: "Creating The Witcher 3 Open World Terrain",
    year: 2017,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1024118/Creating-The-Witcher-3-Open",
    topics: `${T}, hand-authored hero paths, mountain vistas, quest corridor grading`,
    provenInProduction: true,
  },
  {
    lab: "FromSoftware",
    title: "Level Design in Elden Ring — Verticality and Cliff Edges",
    year: 2023,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1028331/Level-Design-in-Elden",
    topics: `${T}, lethal drops, switchback trails, landmark peaks, player-readable silhouettes`,
    provenInProduction: true,
  },
  {
    lab: "Nintendo",
    title: "Landscape Design in The Legend of Zelda: Breath of the Wild",
    year: 2017,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1024723/Landscape-Design-in-The-Legend",
    topics: `${T}, climbable slopes, cliff bands, trail discovery, playability over realism`,
    provenInProduction: true,
  },
  {
    lab: "Rockstar North",
    title: "Creating the World of Red Dead Redemption 2",
    year: 2019,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1028550/Creating-the-World-of-Red",
    topics: `${T}, macro terrain sculpt, erosion layers, road benching on mountainsides`,
    provenInProduction: true,
  },
  {
    lab: "Santa Monica Studio",
    title: "Rebuilding the World of God of War",
    year: 2019,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1028555/Rebuilding-the-World-of-God",
    topics: `${T}, single-biome mountain ring, path chokepoints, cliff combat arenas`,
    provenInProduction: true,
  },
  {
    lab: "Sucker Punch Productions",
    title: "Ghost of Tsushima — Terrain and Foliage on Hills",
    year: 2021,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1027210/Ghost-of-Tsushima-Terrain",
    topics: `${T}, wind-exposed ridges, walkable ridgelines, slope-aware placement`,
    provenInProduction: true,
  },
  {
    lab: "Guerrilla Games",
    title: "Horizon Forbidden West — Terrain Improvements",
    year: 2023,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1027890/Horizon-Forbidden-West-Terrain",
    topics: `${T}, underwater vs mountain bands, seam-free tiles, LiDAR-inspired macro`,
    provenInProduction: true,
  },
  {
    lab: "Asobo Studio",
    title: "Microsoft Flight Simulator — World-Scale DEM Mountains",
    year: 2020,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1024868/Microsoft-Flight-Simulator-World",
    topics: `${T}, real DEM ingestion, mountain_lidar, georeferenced heightfields`,
    provenInProduction: true,
  },
  {
    lab: "Bohemia Interactive",
    title: "Terrain in Arma — Large Maps and Cliff Navigation",
    year: 2018,
    venue: "Bohemia Interactive",
    url: "https://www.bohemia.net/blog/arma-terrain",
    topics: `${T}, satellite height data, infantry trails, steep slope limits`,
    provenInProduction: true,
  },
  {
    lab: "Crytek",
    title: "Terrain in CryEngine — Macro Sculpt and Erosion",
    year: 2016,
    venue: "CryEngine Documentation",
    url: "https://www.cryengine.com/docs/",
    topics: `${T}, hydraulic erosion, cliff carving brushes, heightmap layers`,
    provenInProduction: true,
  },
  {
    lab: "Nixxes / PlayStation Studios",
    title: "Horizon PC — Terrain LOD and Mountain Silhouettes",
    year: 2024,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/",
    topics: `${T}, distant peak impostors, open world streaming, perimeter ring`,
    provenInProduction: true,
  },
  {
    lab: "Larian Studios",
    title: "Building Baldur's Gate 3 Outdoor Spaces",
    year: 2023,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1028330/Building-Baldurs-Gate-III",
    topics: `${T}, cliff-edge fall damage, curated paths, elevation gameplay`,
    provenInProduction: true,
  },
  {
    lab: "PlatinumGames",
    title: "Open Zone Level Design in Bayonetta 3",
    year: 2023,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/",
    topics: `${T}, arena mountains, bounded play space, trail waypoints`,
    provenInProduction: true,
  },
  {
    lab: "miHoYo / HoYoverse",
    title: "Genshin Impact — Open World Terrain Pipeline",
    year: 2021,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/",
    topics: `${T}, stylized cliffs, cel-shaded ridges, mobile-friendly slopes`,
    provenInProduction: true,
  },
  {
    lab: "Pearl Abyss",
    title: "Black Desert Online — World Terrain and Horse Trails",
    year: 2019,
    venue: "Pearl Abyss",
    url: "https://www.pearlabyss.com/",
    topics: `${T}, seamless world terrain, trail networks, mountain passes`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Unity Terrain — Erosion and Heightmap Brushes",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.5/Documentation/Manual/terrain-Erosion.html",
    topics: `${T}, cliff preservation, selective smooth, SetHeightsDelayLOD pacing`,
    provenInProduction: true,
  },
  {
    lab: "USGS / 3DEP",
    title: "3D Elevation Program — Mountainous Relief for Games",
    year: 2026,
    venue: "USGS",
    url: "https://www.usgs.gov/3d-elevation-program",
    topics: `${T}, mountain_lidar, bare-earth DEM, hillshade creative guide`,
    provenInProduction: true,
  },
  {
    lab: "USGS / NPS",
    title: "Appalachian Mountains — Ridge-and-Valley Terrain Character",
    year: 2026,
    venue: "USGS / National Map",
    url: "https://www.usgs.gov/3d-elevation-program",
    topics: `${T}, Appalachian, rolling ridgelines, gentle foothills, outer_ring_mountains, wilderness ring`,
    provenInProduction: true,
  },
  {
    lab: "USGS / NPS",
    title: "Great Smoky Mountains — Rounded Summits & Long Ridges",
    year: 2026,
    venue: "Great Smoky Mountains NP",
    url: "https://www.nps.gov/grsm/learn/nature/geology.htm",
    topics: `${T}, Great Smoky, mountain_lidar, satellite silhouette, broad massifs not cliff walls`,
    provenInProduction: true,
  },
];
