/**
 * Open-world / streaming R&D for Option A (Horizon-style zone).
 * Classic GDC/AAA refs included regardless of minResearchYear — see papersForMinYear().
 */
import type { ResearchEntry } from "./research-catalog.js";

const T = "open_world_streaming";

export const OPEN_WORLD_STREAMING_PAPERS: ResearchEntry[] = [
  // —— Batch 1: streaming architecture, Unity, AAA, indie, MMO, AI ——
  {
    lab: "Guerrilla Games",
    title: "Streaming the World of Horizon Zero Dawn",
    year: 2023,
    venue: "Guerrilla Games Read",
    url: "https://www.guerrilla-games.com/read/Streaming-the-World-of-Horizon-Zero-Dawn",
    topics: `${T}, AAA terrain streaming, Decima engine, memory scheduling`,
    provenInProduction: true,
  },
  {
    lab: "GDC Vault",
    title: "GPU-Based Run-Time Procedural Placement in Horizon Zero Dawn",
    year: 2017,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1024120/GPU-Based-Run-Time-Procedural",
    topics: `${T}, runtime scatter, vegetation placement, procedural world fill`,
    provenInProduction: true,
  },
  {
    lab: "Hello Games",
    title: "Continuous World Generation in No Man's Sky",
    year: 2017,
    venue: "GDC Vault",
    url: "https://gdcvault.com/play/1024265/Continuous-World-Generation-in-No",
    topics: `${T}, procedural infinite terrain, voxel to mesh pipeline, indie scale`,
    provenInProduction: true,
  },
  {
    lab: "Hello Games",
    title: "Building Worlds Using Math(s) — No Man's Sky",
    year: 2017,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1024514/Building-Worlds-Using",
    topics: `${T}, seeded terrain noise, deterministic planets`,
    provenInProduction: true,
  },
  {
    lab: "Epic Games",
    title: "World Partition in Unreal Engine 5",
    year: 2026,
    venue: "Epic Developer Documentation",
    url: "https://dev.epicgames.com/documentation/en-us/unreal-engine/world-partition-in-unreal-engine",
    topics: `${T}, grid cells, HLOD, distance streaming, world building`,
    provenInProduction: true,
  },
  {
    lab: "Epic Games",
    title: "Unreal Engine World Building Guide (World Partition)",
    year: 2026,
    venue: "Epic Developer Community",
    url: "https://dev.epicgames.com/community/learning/knowledge-base/r6wl/unreal-engine-world-building-guide",
    topics: `${T}, data layers, OFPA, spatial load, production pitfalls`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Addressables — Load Scene (additive streaming)",
    year: 2026,
    venue: "Unity Package Manual",
    url: "https://docs.unity3d.com/Packages/com.unity.addressables@2.0/manual/LoadingScenes.html",
    topics: `${T}, chunk scenes, async load, Unity implementation`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Entities — Scene streaming LoadSceneAsync",
    year: 2026,
    venue: "Unity Entities Manual",
    url: "https://docs.unity3d.com/Packages/com.unity.entities@6.5/manual/streaming-loading-scenes.html",
    topics: `${T}, DOTS sections, large world memory`,
    provenInProduction: true,
  },
  {
    lab: "Meta",
    title: "Unity asset streaming sample (grid LOD + Addressables)",
    year: 2026,
    venue: "Meta Horizon Developers",
    url: "https://developers.meta.com/horizon/documentation/unity/unity-sample-asset-streaming",
    topics: `${T}, grid subscenes, LOD preload, VR open world`,
    provenInProduction: true,
  },
  {
    lab: "Indie / Community",
    title: "Practical Open World Streaming Approaches For All Platforms",
    year: 2026,
    venue: "Slashskill",
    url: "https://www.slashskill.com/practical-open-world-streaming-approaches-for-all-platforms/",
    topics: `${T}, chunk size budgets, mobile console PC, predictive loading`,
    provenInProduction: true,
  },
  {
    lab: "Indie / Community",
    title: "Streaming in Games (grid vs volumes)",
    year: 2025,
    venue: "Guillermo Báez Blog",
    url: "https://www.guillermobaez.com/blog/streaming-in-games",
    topics: `${T}, grid cells, streaming volumes, UE World Partition comparison`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Unity Discussions — 3D open world performance",
    year: 2025,
    venue: "Unity Discussions",
    url: "https://discussions.unity.com/t/3d-open-world-performance-where-do-i-even-start/1682649",
    topics: `${T}, floating origin, terrain streaming, indie pitfalls`,
    provenInProduction: true,
  },
  {
    lab: "Princeton VL",
    title: "Infinigen — Infinite Photorealistic Worlds",
    year: 2023,
    venue: "CVPR / infinigen.org",
    url: "https://infinigen.org/",
    topics: `${T}, procedural infinite worlds, terrain generation, research PCG`,
    provenInProduction: true,
  },
  {
    lab: "Princeton VL",
    title: "Infinite Photorealistic Worlds (arXiv)",
    year: 2023,
    venue: "arXiv",
    url: "https://arxiv.org/abs/2306.09310",
    topics: `${T}, procedural terrain, unlimited variation`,
    provenInProduction: false,
  },
  {
    lab: "AAAI",
    title: "WorldGrow: Generating Infinite 3D World",
    year: 2026,
    venue: "AAAI 2026",
    url: "https://ojs.aaai.org/index.php/AAAI/article/view/37571",
    topics: `${T}, AI world generation, block inpainting, infinite scenes`,
    provenInProduction: false,
  },
  {
    lab: "Research",
    title: "WorldGen: Text to Traversable 3D Worlds",
    year: 2025,
    venue: "arXiv HTML",
    url: "https://arxiv.org/html/2511.16825",
    topics: `${T}, AI layout, traversable worlds, procedural constraints`,
    provenInProduction: false,
  },
  {
    lab: "Research",
    title: "InfiniteDiffusion — Terrain Diffusion (infinite terrain)",
    year: 2025,
    venue: "Project Page",
    url: "https://xandergos.github.io/terrain-diffusion/",
    topics: `${T}, infinite terrain, seed consistency, Minecraft Unity demo`,
    provenInProduction: false,
  },
  {
    lab: "Research",
    title: "SimWorld Studio — UE5 agent environment generation",
    year: 2026,
    venue: "arXiv HTML",
    url: "https://arxiv.org/html/2605.09423",
    topics: `${T}, AI automation, embodied sim, Cursor-like agents`,
    provenInProduction: false,
  },
  {
    lab: "ESEngine",
    title: "World Streaming module (chunk manager)",
    year: 2025,
    venue: "ESEngine Docs",
    url: "https://esengine.cn/en/modules/world-streaming/",
    topics: `${T}, MMO-style chunks, load radius, prefetch`,
    provenInProduction: true,
  },
  {
    lab: "Godot Community",
    title: "Open World Database (Godot chunk streaming)",
    year: 2025,
    venue: "GitHub",
    url: "https://github.com/DigitallyTailored/Godot-Open-World-Database",
    topics: `${T}, indie chunk streaming, batch load limits`,
    provenInProduction: true,
  },
  {
    lab: "WoW Dev / Community",
    title: "World Tiles and Chunks (MMO terrain hierarchy)",
    year: 2025,
    venue: "DeepWiki / noggit3",
    url: "https://deepwiki.com/wowdev/noggit3/2.1-world-tiles-and-chunks",
    topics: `${T}, MMO terrain tiles, ADT chunks, hierarchical scale`,
    provenInProduction: true,
  },
  {
    lab: "Indie MMO Design",
    title: "So You Want to Build an MMO — World Design",
    year: 2026,
    venue: "Medium",
    url: "https://medium.com/@alexander.bakharev_16063/so-you-want-to-build-an-mmo-8-18-world-design-level-architecture-c07798d17f1c",
    topics: `${T}, server meshing, zoning, scope warning`,
    provenInProduction: true,
  },
  {
    lab: "ResearchGate",
    title: "Open World Streaming — automatic memory management",
    year: 2016,
    venue: "ResearchGate",
    url: "https://www.researchgate.net/publication/303998274_Open_World_Streaming_Automatic_memory_management_in_open_world_games_without_loading_screens",
    topics: `${T}, world streamer, grid nodes, classic architecture`,
    provenInProduction: true,
  },
  {
    lab: "Ubisoft",
    title: "Far Cry 5 procedural world generation (GDC)",
    year: 2018,
    venue: "Game Developer",
    url: "https://www.gamedeveloper.com/design/video-the-world-generation-tech-behind-i-far-cry-5-i-",
    topics: `${T}, 64m sectors, biome masks, large outdoor worlds`,
    provenInProduction: true,
  },
  {
    lab: "Toxigon",
    title: "UE5 World Partition optimization (cells, HLOD)",
    year: 2025,
    venue: "Toxigon Blog",
    url: "https://toxigon.com/ue5-world-partition-optimization",
    topics: `${T}, cell size tuning, biome streaming distance, HLOD`,
    provenInProduction: true,
  },
  {
    lab: "BitSoul",
    title: "UE5 World Partition stream 3D assets",
    year: 2025,
    venue: "BitSoul Blog",
    url: "https://bitsoulhosting.com/marketplace/blog/ue5-world-partition-streaming-3d-assets-open-world",
    topics: `${T}, 128m cells, loading range, open world template`,
    provenInProduction: true,
  },
  {
    lab: "GitHub",
    title: "godot-genre-open-world agent skill",
    year: 2025,
    venue: "GitHub",
    url: "https://github.com/thedivergentai/gd-agentic-skills/blob/main/skills/godot-genre-open-world/SKILL.md",
    topics: `${T}, floating origin, chunk streaming, density over size`,
    provenInProduction: true,
  },
  {
    lab: "PocketMine",
    title: "World Management — chunk loaders",
    year: 2025,
    venue: "PocketMine Docs",
    url: "https://pmmp-pocketmine-mp.mintlify.app/concepts/worlds",
    topics: `${T}, 16x16 chunks, async population, multiplayer`,
    provenInProduction: true,
  },
  {
    lab: "The Melding Wars",
    title: "Zone and gtchunk file layout",
    year: 2025,
    venue: "GitHub Wiki",
    url: "https://github.com/themeldingwars/Documentation/wiki/zone",
    topics: `${T}, MMO zone chunks 512m, chunk references`,
    provenInProduction: true,
  },
  // —— Batch 2: gaps, floating origin, terrain tech, landmark design ——
  {
    lab: "Game Developer",
    title: "How continuous world generation works in No Man's Sky",
    year: 2017,
    venue: "Game Developer",
    url: "https://www.gamedeveloper.com/programming/video-how-continuous-world-generation-works-in-i-no-man-s-sky-i-",
    topics: `${T}, NMS pipeline, programmer bridge doc, procedural planets`,
    provenInProduction: true,
  },
  {
    lab: "Indie / Community",
    title: "Level Streaming in Unity (YouTube tutorial)",
    year: 2025,
    venue: "YouTube",
    url: "https://www.youtube.com/watch?v=JOPgk3D66kA",
    topics: `${T}, LoadSceneAsync, UnloadSceneAsync, indie pattern`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Addressables — Memory Management",
    year: 2026,
    venue: "Unity Package Manual",
    url: "https://docs.unity3d.com/Packages/com.unity.addressables@1.3/manual/MemoryManagement.html",
    topics: `${T}, bundle refcount, chunk unload leaks, production discipline`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Entities — Loading scenes at runtime (streaming)",
    year: 2026,
    venue: "Unity Entities Manual",
    url: "https://docs.unity3d.com/Packages/com.unity.entities@0.50/manual/loading_scenes.html",
    topics: `${T}, async section load, non-blocking gameplay`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Unity Discussions — World Building Challenge",
    year: 2025,
    venue: "Unity Discussions",
    url: "https://discussions.unity.com/t/world-building-challenge/886379",
    topics: `${T}, World Machine Houdini cliffs, tile authoring before streaming`,
    provenInProduction: true,
  },
  {
    lab: "GitHub",
    title: "WorldGrow — infinite 3D world growth (code)",
    year: 2026,
    venue: "GitHub",
    url: "https://github.com/world-grow/WorldGrow",
    topics: `${T}, AI block growth, walkable infinite, research export path`,
    provenInProduction: false,
  },
  {
    lab: "Netherlands3D",
    title: "Floating Origin for large real-world coordinates",
    year: 2025,
    venue: "Netherlands3D Docs",
    url: "https://netherlands3d.eu/docs/developers/features/floating-origin/",
    topics: `${T}, floating origin, WGS84 ECEF, precision shift all objects`,
    provenInProduction: true,
  },
  {
    lab: "Coherence",
    title: "World Origin Shifting (multiplayer floating origin)",
    year: 2025,
    venue: "Coherence Docs",
    url: "https://docs.coherence.io/2.1/manual/advanced-topics/big-worlds/world-origin-shifting",
    topics: `${T}, per-client origin, 64-bit absolute coords, future net`,
    provenInProduction: true,
  },
  {
    lab: "Indie / Community",
    title: "Level Streaming in Unity — Breaking Down Open Worlds",
    year: 2025,
    venue: "Drafted by Machines",
    url: "https://daily.jovis.ai/game-development/level-streaming-in-unity-breaking-down-open-worlds/",
    topics: `${T}, loadDistance unloadDistance, additive scenes, occlusion culling`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Terrain.SetNeighbors — seamless tile LOD",
    year: 2026,
    venue: "Unity Scripting API",
    url: "https://docs.unity3d.com/ScriptReference/Terrain.SetNeighbors.html",
    topics: `${T}, multi-tile LOD seams, SurfaceTerrainTileExpansion pattern`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Unity Discussions — seamless terrain SetNeighbors",
    year: 2025,
    venue: "Unity Discussions",
    url: "https://discussions.unity.com/t/seamless-terrain-question/389019",
    topics: `${T}, neighbor wiring both directions, dynamic load at runtime`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Terrain.drawInstanced — instanced terrain renderer",
    year: 2026,
    venue: "Unity Scripting API",
    url: "https://docs.unity3d.com/6000.1/Documentation/ScriptReference/Terrain-drawInstanced.html",
    topics: `${T}, GPU instanced heightmap, many active chunks`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Terrain Settings — Draw Instanced reference",
    year: 2026,
    venue: "Unity Manual",
    url: "https://docs.unity3d.com/Manual/terrain-OtherSettings.html",
    topics: `${T}, per-tile draw toggle, heightmap LOD limits`,
    provenInProduction: true,
  },
  {
    lab: "Indie / Community",
    title: "Streaming Massive Terrains with Geometry Clipmapping",
    year: 2025,
    venue: "Ray's Slice",
    url: "https://raygoe.net/2025/08/29/streaming-massive-terrains-with-geometry-clipmapping/",
    topics: `${T}, clipmap LOD rings, heightmap in vertex shader, beyond Unity Terrain bake`,
    provenInProduction: true,
  },
  {
    lab: "Nintendo / Community",
    title: "Open world level design — spatial flow in Breath of the Wild",
    year: 2017,
    venue: "Radiator Blog",
    url: "https://www.blog.radiator.debacle.us/2017/10/open-world-level-design-spatial.html",
    topics: `${T}, triangle landmarks, gravity funnels, POI density not empty space`,
    provenInProduction: true,
  },
  {
    lab: "Nintendo / Community",
    title: "BotW CEDEC — 120 map sections procedural UI tiles",
    year: 2017,
    venue: "Medium (Matt Walker summary)",
    url: "https://medium.com/@gypsyOtoko/this-is-a-reposting-of-my-twitter-thread-summarizing-articles-of-the-botw-cedec-talks-which-can-be-91e9be85de51",
    topics: `${T}, 120 dynamic sections, nightly texture gen, section streaming mental model`,
    provenInProduction: true,
  },
  {
    lab: "ZeldaMods",
    title: "Breath of the Wild — OpenWorldStage and map units",
    year: 2025,
    venue: "ZeldaMods Wiki",
    url: "https://zeldamods.org/wiki/Overview",
    topics: `${T}, stage/scene model, fixed spawns vs auto placement, kit POI tables`,
    provenInProduction: true,
  },
  {
    lab: "FromSoftware / Press",
    title: "Elden Ring — largest free-form map structure (IGN)",
    year: 2022,
    venue: "IGN",
    url: "https://sea.ign.com/elden-ring/173092/news/elden-ring-how-fromsofts-largest-most-free-form-map-works-summer-of-gaming",
    topics: `${T}, six domains, legacy dungeons in overworld, cave POI cadence`,
    provenInProduction: true,
  },
  {
    lab: "FromSoftware / Community",
    title: "World design lessons from FromSoftware (Elden Ring density)",
    year: 2023,
    venue: "Medium",
    url: "https://medium.com/@Jamesroha/world-design-lessons-from-fromsoftware-78cadc8982df",
    topics: `${T}, overworld plus instanced dungeons, avoid empty zones`,
    provenInProduction: true,
  },
  {
    lab: "Level Design / Community",
    title: "Elden Ring — Erdtree as global landmark compass",
    year: 2022,
    venue: "Benicia Paw",
    url: "https://beniciapaw.com/2022/04/01/elden-ring-how-to-design-an-open-world/",
    topics: `${T}, landmark navigation, vista POI, Option A vista table`,
    provenInProduction: true,
  },
  {
    lab: "Academic",
    title: "Implicit wayfinding in Elden Ring and A Short Hike (thesis)",
    year: 2024,
    venue: "Theseus / Haaga-Helia",
    url: "https://www.theseus.fi/bitstream/10024/904850/2/Grau_Vesna.pdf",
    topics: `${T}, terrain cues, gameplay site placement, trail graph design`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Unity Manual — Occlusion Culling",
    year: 2026,
    venue: "Unity Manual",
    url: "https://docs.unity3d.com/6000.5/Documentation/Manual/OcclusionCulling.html",
    topics: `${T}, per-chunk bake, reduce draw in loaded ring`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Unity Manual — LOD Groups",
    year: 2026,
    venue: "Unity Manual",
    url: "https://docs.unity3d.com/6000.5/Documentation/Manual/LevelOfDetail.html",
    topics: `${T}, prop LOD rings, distant chunk impostors`,
    provenInProduction: true,
  },
  {
    lab: "Procedural Worlds",
    title: "Gaia — terrain stamping and world creation (Unity)",
    year: 2025,
    venue: "Procedural Worlds",
    url: "https://procedural-worlds.com/products/gaia/",
    topics: `${T}, tile stamping workflow, compare to Florida DEM per chunk`,
    provenInProduction: true,
  },
  {
    lab: "Rockstar / GDC",
    title: "Building the Beautiful World of Red Dead Redemption 2",
    year: 2019,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1025313/Building-the-Beautiful-World-of-Red-Dead-Redemption-2-A-Exhaustive-Approach-to-Rendering",
    topics: `${T}, AAA terrain rendering, distant HLOD quality bar`,
    provenInProduction: true,
  },
  {
    lab: "Epic Games",
    title: "World Origin Rebasing (Unreal Engine)",
    year: 2026,
    venue: "Epic Developer Documentation",
    url: "https://dev.epicgames.com/documentation/en-us/unreal-engine/world-origin-rebasing-in-unreal-engine",
    topics: `${T}, cross-engine floating origin reference, 4km zone beyond 5k units`,
    provenInProduction: true,
  },
  {
    lab: "GitHub",
    title: "Unity URP procedural DrawMeshInstancedIndirect vegetation",
    year: 2025,
    venue: "GitHub",
    url: "https://github.com/AkilarLiao/UnityURP-Procedural-DrawMeshInstancedIndirect",
    topics: `${T}, GPU scatter per chunk, FilterMap masks, mobile-safe instancing`,
    provenInProduction: true,
  },
  {
    lab: "Ubisoft",
    title: "Assassin's Creed Unity — procedural world design (GDC)",
    year: 2014,
    venue: "Game Developer",
    url: "https://www.gamedeveloper.com/audio/video-creation-world-of-assassin-s-creed-unity-with-procedural-design",
    topics: `${T}, procedural city blocks, modular world units at scale`,
    provenInProduction: true,
  },
  {
    lab: "CD PROJEKT RED / GDC",
    title: "The Witcher 3 — open world design (GDC Vault)",
    year: 2015,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1023017/The-Witcher-3-Open-World-Design",
    topics: `${T}, quest density, handcrafted POI in large zone, Option A narrative hooks`,
    provenInProduction: true,
  },
  {
    lab: "Unity Technologies",
    title: "Terrain Tools package — multi-tile authoring",
    year: 2026,
    venue: "Unity Package Manual",
    url: "https://docs.unity3d.com/Packages/com.unity.terrain-tools@5.0/manual/index.html",
    topics: `${T}, Terrain Toolbox, batch heightmap across tiles, editor scale-up`,
    provenInProduction: true,
  },
];
