import type { PipelinePhaseDef } from "./pipeline-phase-types.js";

const polishFocus: Record<string, string> = {
  polish_01_compile_refresh: "Refresh CaveBuildCompileDiagnostics.json — zero blocking CS errors before polish.",
  polish_02_research_brief: "Sync ResearchCache execution brief for terrain + playtest categories.",
  polish_03_url_digest:
    "Use CaveBuildResearchUrlDigest.json + urlDigests in CaveBuildResearch.json — cite Florida LiDAR, Unity terrain, playtest bot papers.",
  polish_04_prebuild_ladder: "Pre-build ladder ≥88/B+ — compile, tooling, scene ground, prefab catalog.",
  polish_05_terrain_dem: "DEM georeference stamp from ResearchCache hillshade manifest.",
  polish_06_terrain_smooth_a: "Outer ring smooth pass A — no new craters.",
  polish_07_terrain_smooth_b: "Outer ring smooth pass B — playable slopes.",
  polish_08_crater_detect: "Score heightfield — flag crater/spike cells from radial water bowls.",
  polish_09_crater_repair: "Repair crater cells + center bowl — fill only, no teleport cave.",
  polish_10_radial_guard: "Radial sculpt outside inner preserve disk only.",
  polish_11_heightfield_grade: "Run terrain build ladder heightfield rung.",
  polish_12_playable_slopes: "Trail bench flatten — human walkable.",
  polish_13_trail_bench: "Roads/trails refinement pass.",
  polish_14_water_basins: "Water basins + LiDAR touch-up — no floating hydro.",
  polish_15_terrain_final_smooth: "Final smooth before NavMesh.",
  polish_16_surface_navmesh: "Bake surface NavMesh — agent matches Player CharacterController radius.",
  polish_17_surface_route_probe: "Surface route probe to cave mouth — fix trail gaps.",
  polish_18_prop_trees: "Place trees one-by-one along trail sectors.",
  polish_19_prop_grass: "Place grass/ground cover only.",
  polish_20_prop_bushes: "Place bushes/understory only.",
  polish_21_prop_ground_cover: "Flowers/ground cover — hillshade green belts.",
  polish_22_prop_rocks_optional: "Optional rocks — skip if catalog empty.",
  polish_23_surface_enemy_plan: "Plan humanoid surface enemy scatter on NavMesh.",
  polish_24_surface_enemies: "Ensure SurfaceTerrainEnemySpawner placement.",
  polish_25_cave_roof_audit: "Strip roof shells blocking sky at openings.",
  polish_26_entry_shrines: "Entry shrines at all cave openings.",
  polish_27_cave_xz_lock: "Lock cave world XZ — depth-only mouth snap thereafter.",
  polish_28_cave_mouth_align: "Align cave root to best surface opening sector.",
  polish_29_cave_spawn_pad: "Walkways + spawn reachability.",
  polish_30_cave_walkways: "Player floor collision — no invisible pits.",
  polish_31_cave_floor_collision: "Cave NavMesh bake.",
  polish_32_cave_navmesh: "Additive visual shell route repair only in meat/post-meat.",
  polish_33_visual_shell_additive: "Cave materials PBR repair.",
  polish_34_cave_materials: "Adventure cave lighting along maze layout.",
  polish_35_cave_lighting: "Mob spawners along route.",
  polish_36_cave_mob_spawners: "Combat playtest bot component on cave root.",
  polish_37_combat_prefab_wire: "Player tagged + combat wiring.",
  polish_38_player_combat_wire: "HumanoidDimensions from Player CC.",
  polish_39_humanoid_scale: "Performance budget — no extra mesh spam.",
  polish_40_performance_budget: "Atmosphere/fog layout fix.",
  polish_41_fog_atmosphere: "PlayableWorldStatus gate.",
  polish_42_packaging_gate: "SurfacePlaytestValidator export.",
  polish_43_surface_validator: "Cave route probe export.",
  polish_44_cave_route_probe: "Combat probe collects on Play Mode exit.",
  polish_45_combat_probe_export: "Full terrain ladder grade-fix loop.",
  polish_46_terrain_ladder_full: "Quality report snapshot for polish.",
  polish_47_quality_meat_snapshot: "PlayerCameraRig / spectator prep.",
  polish_48_spectator_cam_prep: "CavePlaytestBotController on cave root.",
  polish_49_playtest_bot_avatar: "Route + combat bots ready — do not enter Play Mode until phase 60.",
  polish_50_bot_combat_ready: "Terrain ladder pass 2.",
  polish_51_terrain_ladder_pass2: "NavMesh rebake.",
  polish_52_navmesh_rebake: "Crater sweep.",
  polish_53_crater_sweep: "Vegetation touch-up pass.",
  polish_54_props_touchup: "Confirm pre-build ladder still ≥88.",
  polish_55_prebuild_ladder_confirm: "Playable world gate final.",
  polish_56_playable_world_gate: "Final surface probe.",
  polish_57_surface_probe_final: "Final cave quality export.",
  polish_58_cave_quality_export: "Export research action plan for bot handoff.",
  polish_59_research_action_plan: "Schedule playtest bot — Enter Play Mode.",
  polish_60_bot_schedule_ready: "All 60 polish phases complete — run CavePlaytestRouteBotBridge.",
};

export const PLAYTEST_POLISH_PHASES: PipelinePhaseDef[] = Object.entries(polishFocus).map(
  ([id, focus]) => ({
    id,
    title: id.replace(/_/g, " ").replace(/^polish \d+ /, (m) => m.toUpperCase()),
    rung: "pre_build" as const,
    researchCategories: ["terrain", "ground_placement", "visual_reference"],
    webSearchQueries: [
      "Unity 6 terrain polish playable slopes NavMesh",
      "automated game playtesting bot environment QA",
    ],
    jsonPaths: [
      "Assets/EnvironmentKit/Generated/CaveBuildResearch.json",
      "Assets/EnvironmentKit/Generated/CaveBuildResearchUrlDigest.json",
      "Assets/EnvironmentKit/Generated/PlaytestPolishPhaseLog.json",
      "Assets/EnvironmentKit/Generated/SurfaceTerrainBuildLadderReport.json",
    ],
    focus,
  }),
);
