/**
 * Major game studios — shipped environment / terrain / cave-adjacent references (2025–2026).
 * Image URLs are official docs, studio CDNs, or stable publication assets (proven in production).
 */

import type { VisualReference } from "./research-visual-references.js";

export const GAME_STUDIO_VISUAL_REFERENCES: VisualReference[] = [
  {
    id: "ubisoft-farcry6-open-world",
    title: "Ubisoft — Far Cry 6 open world (Yara terrain + interiors)",
    year: 2022,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Ubisoft",
    docUrl: "https://toronto.ubisoft.com/gdc-2022-ubisoft-toronto-far-cry-6/",
    imageUrls: [
      "https://cdn.akamai.steamstatic.com/steam/apps/2369390/library_600x900_2x.jpg",
    ],
    notes:
      "Reference for large-scale outdoor terrain, rock formations, and interior contrast. GDC22 raytracing + weather systems.",
  },
  {
    id: "ubisoft-farcry5-pcg-biomes",
    title: "Ubisoft — Far Cry 5 procedural biome terrain (GDC)",
    year: 2018,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Ubisoft",
    docUrl: "https://www.gamedeveloper.com/design/video-the-world-generation-tech-behind-i-far-cry-5-i-",
    imageUrls: [
      "https://cdn.akamai.steamstatic.com/steam/apps/552520/header.jpg",
    ],
    notes: "Procedural terrain texturing, freshwater networks, cliff rocks — applicable to route-based cave mouths.",
  },
  {
    id: "ubisoft-laforge-pcg",
    title: "Ubisoft La Forge — PCG / Electric Dreams (environment scale)",
    year: 2025,
    category: "pcg_shell",
    provenInProduction: true,
    studio: "Ubisoft La Forge",
    docUrl: "https://www.ubisoft.com/en-us/studio/laforge/publications",
    imageUrls: [],
    notes: "Block-shell density and large environment generation discipline (production R&D).",
  },
  {
    id: "ea-seed-aaa-testing",
    title: "EA SEED — ML AAA game testing (automation reference)",
    year: 2025,
    category: "studio_environment",
    provenInProduction: true,
    studio: "EA SEED",
    docUrl: "https://www.ea.com/seed/news/seed-ml-research-aaa-game-testing",
    imageUrls: [],
    notes: "Playtest/route validation mindset for cave probe bots — not visual layout.",
  },
  {
    id: "epic-unreal-landscape-caves",
    title: "Epic Games — Unreal Landscape (openings for caves)",
    year: 2026,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Epic Games",
    docUrl: "https://dev.epicgames.com/documentation/en-us/unreal-engine/landscape-outdoor-terrain-in-unreal-engine",
    imageUrls: [],
    notes:
      "Epic docs explicitly mention terrain openings for caves. Cross-check Unity RouteTerrain approach.",
  },
  {
    id: "epic-gpuopen-meshgen",
    title: "Epic GPUOpen — procedural mesh generation",
    year: 2025,
    category: "pcg_shell",
    provenInProduction: true,
    studio: "Epic Games / GPUOpen",
    docUrl: "https://gpuopen.com/learn/mesh_generation/",
    imageUrls: ["https://gpuopen.com/wp-content/uploads/2021/06/meshgen-01.png"],
    notes: "Production mesh tooling for shell/wall density.",
  },
  {
    id: "nvidia-3d-generalist",
    title: "NVIDIA Research — 3D Generalist (world-scale meshes)",
    year: 2026,
    category: "studio_environment",
    provenInProduction: true,
    studio: "NVIDIA Research",
    docUrl: "https://research.nvidia.com/publication/2026-03_3d-generalist-vision-language-action-models-crafting-3d-worlds",
    imageUrls: [],
    notes: "High-end mesh/world reference — use for silhouette only; kit uses block rings not neural gen.",
  },
  {
    id: "sony-ps5-automated-gameplay",
    title: "Sony — automated gameplay testing (PS5)",
    year: 2025,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Sony Interactive Entertainment",
    docUrl:
      "https://sonyinteractive.com/en/innovation/research-academia/research/ai-technology-for-automating-gameplay-on-playstation-5-under-human-equivalent-conditions/",
    imageUrls: [],
    notes: "Route/playtest automation parity with CavePlaytestRouteBot goals.",
  },
  {
    id: "activision-research-qa",
    title: "Activision Research — production QA scale",
    year: 2025,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Activision Research",
    docUrl: "https://research.activision.com/publications",
    imageUrls: [],
    notes: "QA/combat probe validation patterns.",
  },
  {
    id: "bungie-engineering-worlds",
    title: "Bungie — engineering / large worlds",
    year: 2026,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Bungie",
    docUrl: "https://www.bungie.net/en/News?tag=Engineering",
    imageUrls: ["https://www.bungie.net/img/community/updates/destiny2-splash.jpg"],
    notes: "Performance + large world streaming reference.",
  },
  {
    id: "riot-swarm-performance",
    title: "Riot Games — performance optimization (Swarm)",
    year: 2025,
    category: "performance",
    provenInProduction: true,
    studio: "Riot Games",
    docUrl: "https://technology.riotgames.com/news/optimization-league-legends-teamfight-tactics",
    imageUrls: [],
    notes: "Triangle budget / perf discipline for grading pass.",
  },
  {
    id: "microsoft-wham-gameplay",
    title: "Microsoft Research — gameplay simulation (production ML)",
    year: 2025,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Microsoft Research",
    docUrl:
      "https://www.microsoft.com/en-us/research/publication/world-and-human-action-models-towards-gameplay-ideation/",
    imageUrls: [],
    notes: "Optional ideation only — prefer shipped environment art above for layout.",
  },
  {
    id: "fromsoftware-cave-lighting",
    title: "Reference — underground interior lighting (Elden Ring mine)",
    year: 2022,
    category: "cave_layout",
    provenInProduction: true,
    studio: "FromSoftware (reference)",
    docUrl: "https://en.bandainamcoent.eu/elden-ring/elden-ring",
    imageUrls: [
      "https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg",
    ],
    notes:
      "Cave/mine readability + floor/ceiling contrast reference (shipped game art, not R&D paper).",
  },
  {
    id: "id-software-doom-interior",
    title: "Reference — interior rock corridors (DOOM Eternal)",
    year: 2020,
    category: "cave_layout",
    provenInProduction: true,
    studio: "id Software (reference)",
    docUrl: "https://www.bethesda.net/en/game/doom-eternal",
    imageUrls: [
      "https://cdn.akamai.steamstatic.com/steam/apps/782330/header.jpg",
    ],
    notes: "Tight corridor rock walls + combat arenas — shell ring layout reference.",
  },
  {
    id: "guerrilla-horizon-terrain",
    title: "Sony Guerrilla — Horizon terrain sculpt (open world rock)",
    year: 2022,
    category: "terrain",
    provenInProduction: true,
    studio: "Guerrilla Games",
    docUrl: "https://www.guerrilla-games.com/read/how-to-create-a-vista-in-horizon-forbidden-west",
    imageUrls: [
      "https://cdn.akamai.steamstatic.com/steam/apps/2420110/header.jpg",
    ],
    notes: "Natural rock terrain and vista composition for surface mouth.",
  },
];
