/**
 * World layout & placement — 30 curated refs (2026-05-29).
 * Doc: Packages/com.cursor.environment-authoring-kit/docs/RESEARCH_WORLD_LAYOUT_PLACEMENT.md
 */
import type { VisualReference } from "./research-visual-references.js";

export const WORLD_LAYOUT_PLACEMENT_REFERENCES: VisualReference[] = [
  {
    id: "wlp-01-farcry-gdc-toolchain",
    title: "Far Cry 5 — GDC procedural world tool chain (mask order)",
    year: 2018,
    category: "pcg_shell",
    provenInProduction: true,
    studio: "Ubisoft",
    docUrl: "https://tools.engineer/gdc2018-procedural-world-generation-of-far-cry-5",
    imageUrls: ["https://cdn.akamai.steamstatic.com/steam/apps/552520/header.jpg"],
    notes:
      "world_layout_placement | pipeline_masks: 64×64 m sectors; freshwater→cliffs→biomes mask chain. Kit: surface phases before cave queue.",
  },
  {
    id: "wlp-02-farcry-gamedeveloper-video",
    title: "Far Cry 5 — world generation tech (video)",
    year: 2018,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Ubisoft",
    docUrl: "https://www.gamedeveloper.com/design/video-the-world-generation-tech-behind-i-far-cry-5-i-",
    imageUrls: ["https://cdn.akamai.steamstatic.com/steam/apps/552520/header.jpg"],
    notes:
      "world_layout_placement | pipeline_masks: shoreline + exclusion masks from freshwater tools before biome scatter.",
  },
  {
    id: "wlp-03-farcry-christianjmills-notes",
    title: "Far Cry 5 — procedural tools notes",
    year: 2018,
    category: "pcg_shell",
    provenInProduction: true,
    docUrl: "https://christianjmills.com/posts/procedural-tools-far-cry-5-notes/",
    imageUrls: [],
    notes:
      "world_layout_placement | pipeline_masks: incremental sector bake vs nightly full regen — analog: one terrain tile per editor frame.",
  },
  {
    id: "wlp-04-epic-pcg-overview",
    title: "Epic — UE5 PCG overview",
    year: 2026,
    category: "pcg_shell",
    provenInProduction: true,
    studio: "Epic Games",
    docUrl: "https://dev.epicgames.com/documentation/en-us/unreal-engine/procedural-content-generation-overview",
    imageUrls: [],
    notes:
      "world_layout_placement | pipeline_masks: topological task order; pin seeds; bake before runtime scatter.",
  },
  {
    id: "wlp-05-strayspark-pcg-production",
    title: "StraySpark — PCG framework production UE5",
    year: 2026,
    category: "pcg_shell",
    provenInProduction: true,
    docUrl: "https://www.strayspark.studio/blog/procedural-content-generation-pcg-framework-production-ue5-7",
    imageUrls: [],
    notes:
      "world_layout_placement | pipeline_masks: separate structural PCG from organic scatter passes.",
  },
  {
    id: "wlp-06-unity-set-neighbors",
    title: "Unity — Terrain.SetNeighbors API",
    year: 2026,
    category: "terrain",
    provenInProduction: true,
    studio: "Unity Technologies",
    docUrl: "https://docs.unity3d.com/ScriptReference/Terrain.SetNeighbors.html",
    imageUrls: [],
    notes:
      "world_layout_placement | terrain_seams: LOD stitch on all four sides + flush after connect.",
  },
  {
    id: "wlp-07-unity-neighbor-terrains-manual",
    title: "Unity — Create Neighbor Terrains",
    year: 2026,
    category: "terrain",
    provenInProduction: true,
    studio: "Unity Technologies",
    docUrl: "https://docs.unity3d.com/Manual/terrain-CreateNeighborTerrains.html",
    imageUrls: [],
    notes:
      "world_layout_placement | terrain_seams: fill heightmap from neighbors; grouping ID for 9-tile grid.",
  },
  {
    id: "wlp-08-bugnet-terrain-holes",
    title: "Bugnet — fix terrain holes at chunk boundaries",
    year: 2025,
    category: "terrain",
    provenInProduction: true,
    docUrl: "https://bugnet.io/blog/fix-unity-terrain-holes-appearing-at-chunk-boundaries",
    imageUrls: [],
    notes:
      "world_layout_placement | terrain_seams: edge height average + identical LOD settings across tiles.",
  },
  {
    id: "wlp-09-unity-terrain-heightmaps",
    title: "Unity 6 — Terrain heightmaps",
    year: 2026,
    category: "terrain",
    provenInProduction: true,
    studio: "Unity Technologies",
    docUrl: "https://docs.unity3d.com/6000.5/Documentation/Manual/terrain-Heightmaps.html",
    imageUrls: [],
    notes:
      "world_layout_placement | terrain_seams: props must sample same heightfield as trails and mouth carve.",
  },
  {
    id: "wlp-10-guerrilla-streaming-hzd",
    title: "Guerrilla — Streaming the World of Horizon Zero Dawn",
    year: 2023,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Guerrilla Games",
    docUrl: "https://www.guerrilla-games.com/read/Streaming-the-World-of-Horizon-Zero-Dawn",
    imageUrls: ["https://cdn.akamai.steamstatic.com/steam/apps/1151640/header.jpg"],
    notes:
      "world_layout_placement | terrain_seams: streaming cells require edge continuity — Option A prerequisite.",
  },
  {
    id: "wlp-11-guerrilla-hzd-vegetation-placement",
    title: "Guerrilla — HZD procedural vegetation placement",
    year: 2017,
    category: "pcg_shell",
    provenInProduction: true,
    studio: "Guerrilla Games",
    docUrl: "https://www.guerrilla-games.com/read/horizon-zero-dawn-procedural-vegetation-placement",
    imageUrls: ["https://cdn.akamai.steamstatic.com/steam/apps/1151640/header.jpg"],
    notes:
      "world_layout_placement | surface_scatter: placement graph after terrain rules; density per biome.",
  },
  {
    id: "wlp-12-guerrilla-gpu-placement",
    title: "Guerrilla — GPU procedural placement HZD",
    year: 2017,
    category: "pcg_shell",
    provenInProduction: true,
    studio: "Guerrilla Games",
    docUrl: "https://www.guerrilla-games.com/read/gpu-based-procedural-placement-in-horizon-zero-dawn",
    imageUrls: ["https://cdn.akamai.steamstatic.com/steam/apps/1151640/header.jpg"],
    notes:
      "world_layout_placement | surface_scatter: roads/terrain theme are inputs to scatter, not regenerated by it.",
  },
  {
    id: "wlp-13-gdc-gpu-placement-hzd",
    title: "GDC — GPU runtime procedural placement (HZD)",
    year: 2017,
    category: "pcg_shell",
    provenInProduction: true,
    docUrl: "https://www.gdcvault.com/play/1024120/GPU-Based-Run-Time-Procedural",
    imageUrls: [],
    notes:
      "world_layout_placement | surface_scatter: interstitial fill between primary points; per-class passes.",
  },
  {
    id: "wlp-14-strayspark-believable-biomes",
    title: "StraySpark — believable biomes rule-based scatter",
    year: 2026,
    category: "pcg_shell",
    provenInProduction: true,
    docUrl: "https://www.strayspark.studio/blog/building-believable-biomes-procedural-scatter",
    imageUrls: [],
    notes:
      "world_layout_placement | surface_scatter: slope, altitude, exclusion zones for trails and structures.",
  },
  {
    id: "wlp-15-strayspark-16km-populate",
    title: "StraySpark — populate 16 km² open world",
    year: 2026,
    category: "pcg_shell",
    provenInProduction: true,
    docUrl: "https://www.strayspark.studio/blog/how-we-populated-16km-open-world",
    imageUrls: [],
    notes:
      "world_layout_placement | surface_scatter: biome layers + min spacing; broad pass then polish.",
  },
  {
    id: "wlp-16-usgs-ds926-floridan",
    title: "USGS DS 926 — Floridan aquifer structural surfaces",
    year: 2012,
    category: "aquifer_structure",
    provenInProduction: true,
    caveStructureOnly: true,
    docUrl: "https://pubs.usgs.gov/ds/0926/",
    imageUrls: [],
    notes:
      "world_layout_placement | cave_surface_join: void below land surface; tube depth not water table.",
  },
  {
    id: "wlp-17-fdep-karst-gis",
    title: "FDEP/FGS — karst GIS layers",
    year: 2026,
    category: "karst_geomorphology",
    provenInProduction: true,
    region: "florida",
    caveStructureOnly: true,
    docUrl: "https://geodata.dep.state.fl.us/search?layout=grid&tags=karst",
    imageUrls: [],
    notes:
      "world_layout_placement | cave_surface_join: sinkhole/mouth placement at surface features.",
  },
  {
    id: "wlp-18-unity-terrain-paint-texture",
    title: "Unity 6 — Terrain paint texture at entrance",
    year: 2026,
    category: "terrain",
    provenInProduction: true,
    studio: "Unity Technologies",
    docUrl: "https://docs.unity3d.com/6000.5/Documentation/Manual/terrain-PaintTexture.html",
    imageUrls: [],
    notes: "world_layout_placement | cave_surface_join: rock/dirt ring after height carve at mouth.",
  },
  {
    id: "wlp-19-epic-landscape-outdoor",
    title: "Epic — Landscape outdoor terrain (cave openings)",
    year: 2026,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Epic Games",
    docUrl: "https://dev.epicgames.com/documentation/en-us/unreal-engine/landscape-outdoor-terrain-in-unreal-engine",
    imageUrls: [],
    notes: "world_layout_placement | cave_surface_join: height blend at terrain hole edges.",
  },
  {
    id: "wlp-20-ezengine-proc-placement",
    title: "ezEngine — procedural object placement (HZD-inspired)",
    year: 2026,
    category: "pcg_shell",
    provenInProduction: true,
    docUrl: "https://ezengine.net/pages/docs/terrain/procedural/procedural-object-placement.html",
    imageUrls: [],
    notes:
      "world_layout_placement | cave_surface_join: placement rules gated on terrain + material masks.",
  },
  {
    id: "wlp-21-nvidia-fly-fail-fix",
    title: "NVIDIA — Fly, Fail, Fix iterative level repair",
    year: 2025,
    category: "studio_environment",
    provenInProduction: true,
    studio: "NVIDIA Research",
    docUrl: "https://arxiv.org/abs/2507.12666",
    imageUrls: [],
    notes:
      "world_layout_placement | validation_grading: playtest→patch→retry; meat loop analog.",
  },
  {
    id: "wlp-22-ea-seed-aaa-testing",
    title: "EA SEED — ML AAA game testing",
    year: 2025,
    category: "studio_environment",
    provenInProduction: true,
    studio: "EA SEED",
    docUrl: "https://www.ea.com/seed/news/seed-ml-research-aaa-game-testing",
    imageUrls: [],
    notes: "world_layout_placement | validation_grading: route probes as regression gates.",
  },
  {
    id: "wlp-23-sony-automated-gameplay",
    title: "Sony — automated gameplay testing PS5",
    year: 2025,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Sony Interactive Entertainment",
    docUrl:
      "https://sonyinteractive.com/en/innovation/research-academia/research/ai-technology-for-automating-gameplay-on-playstation-5-under-human-equivalent-conditions/",
    imageUrls: [],
    notes: "world_layout_placement | validation_grading: traversal coverage on open surface tiles.",
  },
  {
    id: "wlp-24-activision-research-qa",
    title: "Activision Research — production QA",
    year: 2025,
    category: "studio_environment",
    provenInProduction: true,
    studio: "Activision Research",
    docUrl: "https://research.activision.com/publications",
    imageUrls: [],
    notes: "world_layout_placement | validation_grading: tiered ship gates on layout failures.",
  },
  {
    id: "wlp-25-kit-commercial-grading",
    title: "Environment Kit — commercial production grading tiers",
    year: 2026,
    category: "studio_environment",
    provenInProduction: true,
    docUrl:
      "https://github.com/JacobForges/environment-authoring-kit/blob/main/Packages/com.cursor.environment-authoring-kit/docs/COMMERCIAL-PRODUCTION-GRADING.md",
    imageUrls: [],
    notes: "world_layout_placement | validation_grading: target Beta+ layout before Option A streaming.",
  },
  {
    id: "wlp-26-elden-wayfinding-thesis",
    title: "Thesis — implicit wayfinding (Elden Ring)",
    year: 2024,
    category: "cave_layout",
    provenInProduction: true,
    docUrl: "https://www.theseus.fi/bitstream/10024/904850/2/Grau_Vesna.pdf",
    imageUrls: [],
    notes: "world_layout_placement | poi_wayfinding: landmark spacing + terrain cues without UI.",
  },
  {
    id: "wlp-27-gdc-hzd-tools-pipeline",
    title: "GDC — Creating tools pipeline for HZD",
    year: 2017,
    category: "pcg_shell",
    provenInProduction: true,
    docUrl: "https://www.gdcvault.com/play/1024124/Creating-a-Tools-Pipeline-for",
    imageUrls: [],
    notes: "world_layout_placement | poi_wayfinding: artist rules drive runtime placement graphs.",
  },
  {
    id: "wlp-28-sidefx-heightfield-scatter",
    title: "SideFX — Heightfield scatter SOP",
    year: 2026,
    category: "terrain",
    provenInProduction: true,
    studio: "SideFX",
    docUrl: "https://www.sidefx.com/docs/houdini/heightfields/scattersop.html",
    imageUrls: [],
    notes: "world_layout_placement | poi_wayfinding: scatter points separate from heightfield mesh.",
  },
  {
    id: "wlp-29-sidefx-heightfield-creation",
    title: "SideFX — Heightfield creation",
    year: 2026,
    category: "terrain",
    provenInProduction: true,
    studio: "SideFX",
    docUrl: "https://www.sidefx.com/docs/houdini/heightfields/creation.html",
    imageUrls: [],
    notes: "world_layout_placement | poi_wayfinding: stabilize macro terrain before detail/scatter.",
  },
  {
    id: "wlp-30-springer-vegetation-coverage",
    title: "Springer — procedural vegetation max coverage",
    year: 2022,
    category: "pcg_shell",
    provenInProduction: true,
    docUrl: "https://doi.org/10.1007/s11042-022-12107-8",
    imageUrls: [],
    notes:
      "world_layout_placement | poi_wayfinding: spacing constraints / Poisson-style non-overlap disks.",
  },
];
