/**
 * Surface prop placement — per-tile scatter, slope masks, trail corridors (not cliff rings).
 * Category: surface_props. Read during surface_vegetation_intelligent and prop_* rungs.
 */
import type { ResearchEntry } from "./research-catalog.js";

const C = "surface_props";

export const SURFACE_PROP_PLACEMENT_PAPERS: ResearchEntry[] = [
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Terrain detail meshes (grass/rocks on terrain)",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/terrain-Details.html",
    topics: `${C}, terrain details, detail mesh, grass, rock, per terrain tile`,
    provenInProduction: true,
    imageUrls: ["https://docs.unity3d.com/6000.0/Documentation/uploads/Main/terrain-Details-Add.png"],
    notes:
      "Use DetailPrototype / Paint Details for ground cover on walkable bands. Do NOT use Details on vertical cliff-only tiles without slope gate.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Terrain trees and tree prototypes",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/terrain-Trees.html",
    topics: `${C}, terrain trees, TreePrototype, forest ring, outer tiles only`,
    provenInProduction: true,
    notes: "Paint trees on foothill/horizon tiles with max slope filter; skip play disk center preserve band.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Paint Trees tool",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/terrain-PaintTrees.html",
    topics: `${C}, paint trees, brush, density, terrain authoring`,
    provenInProduction: true,
    notes: "Kit analog: SurfaceIntelligentPropPlacer + trail corridor mask before random scatter.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — GPU instancing for dense props",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/GPUInstancing.html",
    topics: `${C}, GPU instancing, draw calls, grass, rocks, performance`,
    provenInProduction: true,
    notes: "Batch ground cover on large worlds; pair with per-tile scatter caps from hardware budget.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Prefabs workflow for environment props",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/Prefabs.html",
    topics: `${C}, prefab, prop, instantiate, environment kit`,
    provenInProduction: true,
    notes: "Use PrefabUtility.InstantiatePrefab under per-tile roots; register undo for automated passes.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Terrain.SampleHeight for prop grounding",
    year: 2026,
    venue: "Unity 6 Scripting",
    url: "https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Terrain.SampleHeight.html",
    topics: `${C}, sample height, snap to ground, wxz, every terrain tile`,
    provenInProduction: true,
    notes: "MANDATORY: every prop spawn calls SampleHeight on the owning tile terrain before SetPosition.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Physics.Raycast downward placement validation",
    year: 2026,
    venue: "Unity 6 Scripting",
    url: "https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Physics.Raycast.html",
    topics: `${C}, raycast, ground mask, reject floating props, cliff face`,
    provenInProduction: true,
    notes: "Reject hits when surface normal.y < slope threshold (vertical wall). Retry with inward offset.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — TerrainData.GetSteepness slope filter",
    year: 2026,
    venue: "Unity 6 Scripting",
    url: "https://docs.unity3d.com/6000.0/Documentation/ScriptReference/TerrainData.GetSteepness.html",
    topics: `${C}, steepness, slope mask, no props on cliff, walkable only`,
    provenInProduction: true,
    notes: "Do not scatter when GetSteepness > 35–42° unless explicitly rock prefab on peak dressing pass.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Splines — place objects along paths",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/splines-overview.html",
    topics: `${C}, splines, trail corridor, labyrinth bench, mouth approach`,
    provenInProduction: true,
    notes: "Trail and labyrinth spines are prop corridors — higher density along polylines, not uniform tile fill.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — NavMesh — keep props off agent walkable cliffs",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/nav-BuildingNavMesh.html",
    topics: `${C}, navmesh, prop clearance, walkable, obstacle`,
    provenInProduction: true,
    notes: "Props are cosmetic unless tagged obstacle — never block NavMesh bake on play disk.",
  },
  {
    lab: "Guerrilla Games",
    title: "GDC — Horizon Zero Dawn vegetation placement rules",
    year: 2026,
    venue: "GDC / Guerrilla",
    url: "https://www.guerrilla-games.com/read/how-horizon-zero-dawn-raises-the-bar-for-vegetation",
    topics: `${C}, vegetation rules, biome mask, GPU placement, AAA`,
    provenInProduction: true,
    notes: "Rule-based placement from terrain masks — kit uses slope + height + distance-to-trail, not pure random.",
  },
  {
    lab: "Ubisoft",
    title: "Far Cry 5 — biome-driven prop density (freshwater vs cliff)",
    year: 2026,
    venue: "Ubisoft / GDC",
    url: "https://www.gdcvault.com/play/1025540/Building-Worlds-Using-Systems",
    topics: `${C}, far cry, biome, cliff vs meadow, density curve`,
    provenInProduction: true,
    notes: "Cliff biomes get rock/dead props only; meadows get grass/trees — never uniform cliff ring props.",
  },
  {
    lab: "SideFX",
    title: "Houdini — heightfield scatter points (mask-driven)",
    year: 2026,
    venue: "SideFX Docs",
    url: "https://www.sidefx.com/docs/houdini/heightfields/scattersop.html",
    topics: `${C}, houdini scatter, mask, density, terrain pipeline`,
    provenInProduction: true,
    notes: "Scatter density follows masks — analog: alphamap + slope before Instantiate in Unity.",
  },
  {
    lab: "Hello Games",
    title: "No Man's Sky — deterministic prop scatter from seed",
    year: 2026,
    venue: "Hello Games / GDC",
    url: "https://www.youtube.com/watch?v=RdN_Yr0H7dk",
    topics: `${C}, seed stable, per planet tile, reproducible scatter`,
    provenInProduction: true,
    notes: "Per-tile RNG derived from world seed + tile offset — FullWorld must reproduce scatter across rebuilds.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Detail density and noise spread",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/terrain-Grass.html",
    topics: `${C}, grass texture, detail layer, noise, ground cover`,
    provenInProduction: true,
    notes: "Prefer detail meshes for small cover on foothills; prefab scatter for hero plants on trails.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — LayerMask ground-only raycasts",
    year: 2026,
    venue: "Unity 6 Scripting",
    url: "https://docs.unity3d.com/6000.0/Documentation/ScriptReference/LayerMask.html",
    topics: `${C}, layer mask, Ground tag, terrain only, prop spawn`,
    provenInProduction: true,
    notes: "Raycast Terrain/Ground layers only — ignore cave shell and blockout geometry.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Terrain alphamap slope painting (rock vs grass)",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/terrain-Textures.html",
    topics: `${C}, alphamap, slope paint, rock layer, grass layer`,
    provenInProduction: true,
    notes: "Align prop categories with splat: grass props only where grass weight > 0.35 on walkable slopes.",
  },
  {
    lab: "Electronic Arts",
    title: "EA SEED — automated world building placement",
    year: 2026,
    venue: "EA SEED",
    url: "https://www.ea.com/seed/news/seed-automated-world-building",
    topics: `${C}, automated placement, world building, rules, AAA`,
    provenInProduction: true,
    notes: "Placement is constraint-solved — use rules (slope, height, distance) not fill every cell.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — CullingGroup for open-world props",
    year: 2026,
    venue: "Unity 6 Scripting",
    url: "https://docs.unity3d.com/6000.0/Documentation/ScriptReference/CullingGroup.html",
    topics: `${C}, culling, LOD, open world, performance`,
    provenInProduction: true,
    notes: "Per-tile prop roots enable disabling distant tile children when streaming (future).",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Terrain Tools package (brush scatter)",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/Packages/com.unity.terrain-tools@5.0/manual/index.html",
    topics: `${C}, terrain tools, brush, scatter, authoring`,
    provenInProduction: true,
    notes: "Reference for artist-driven scatter; kit automates via SurfaceIntelligentPropPlacer instead.",
  },
  {
    lab: "NVIDIA",
    title: "GPUOpen — terrain and foliage best practices",
    year: 2026,
    venue: "GPUOpen",
    url: "https://gpuopen.com/learn/optimized-rendering-vegetation/",
    topics: `${C}, foliage, LOD, batching, open world`,
    provenInProduction: true,
    notes: "Cluster props by tile; avoid spanning seam with single giant parent transform.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Poisson-like spacing (manual jitter)",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/terrain-Details.html",
    topics: `${C}, poisson, jitter, min spacing, natural scatter`,
    provenInProduction: true,
    notes: "Reject spawn if distance to existing prop < minSpacing — per tile spatial hash.",
  },
  {
    lab: "Environment Authoring Kit",
    title: "Kit — SurfaceIntelligentPropPlacer per-tile pass",
    year: 2026,
    venue: "Environment Authoring Kit",
    url: "https://github.com/cursor/environment-authoring-kit/blob/main/Editor/Blockout/SurfaceIntelligentPropPlacer.cs",
    topics: `${C}, SurfaceIntelligentPropPlacer, per terrain tile, intelligent, not random`,
    provenInProduction: true,
    notes:
      "ONE paced pass per tile: collect all terrains (play+foothill+peak), slope filter, trail bias. Extend — do not replace with global random.",
  },
  {
    lab: "Environment Authoring Kit",
    title: "Kit — SurfaceTerrainPropPlacementRegion",
    year: 2026,
    venue: "Environment Authoring Kit",
    url: "https://github.com/cursor/environment-authoring-kit/blob/main/Editor/Blockout/SurfaceTerrainPropPlacementRegion.cs",
    topics: `${C}, placement region, extent, play disk, tile bounds`,
    provenInProduction: true,
    notes: "Use region helpers to clamp scatter to tile AABB; iterate every terrain in grid manifest.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — InstantiatePrefab in editor pipeline",
    year: 2026,
    venue: "Unity 6 Scripting",
    url: "https://docs.unity3d.com/6000.0/Documentation/ScriptReference/PrefabUtility.InstantiatePrefab.html",
    topics: `${C}, PrefabUtility, editor, undo, prop scatter`,
    provenInProduction: true,
    notes: "Always RegisterCreated + parent under tile prop root for clean purge on rebuild.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Terrain neighbors and prop tile ownership",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Terrain.SetNeighbors.html",
    topics: `${C}, terrain neighbors, tile ownership, seam, prop root per tile`,
    provenInProduction: true,
    notes: "Props belong to the tile whose AABB contains XZ; avoid duplicate spawn on seam by inset bounds.",
  },
  {
    lab: "Rockstar / RDR2",
    title: "Open-world ground cover — elevation and slope masks (GDC talk index)",
    year: 2026,
    venue: "GDC Vault",
    url: "https://www.gdcvault.com/play/1027034/Building-Open-Worlds",
    topics: `${C}, open world, ground cover, elevation mask, not cliff ring`,
    provenInProduction: true,
    notes: "Hero props in playable belts; cliffs get rock/decal only — mirrors FullWorld foothill+peak split.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Wind zones for vegetation props",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/class-WindZone.html",
    topics: `${C}, wind, grass, tree, polish`,
    provenInProduction: true,
    notes: "Optional polish pass after placement — does not affect placement rules.",
  },
  {
    lab: "Unity Technologies",
    title: "Unity 6 — Addressables for prop variants (optional)",
    year: 2026,
    venue: "Unity 6 Manual",
    url: "https://docs.unity3d.com/6000.0/Documentation/Manual/com.unity.addressables.html",
    topics: `${C}, addressables, variants, memory, streaming`,
    provenInProduction: true,
    notes: "Future: stream prop prefabs by tile; current kit uses direct prefab references from project.",
  },
  {
    lab: "Environment Authoring Kit",
    title: "Kit — surface_vegetation_intelligent phase contract",
    year: 2026,
    venue: "terrain-pipeline-phases.ts",
    url: "https://github.com/cursor/environment-authoring-kit/blob/main/Tools/cave-grader/terrain-pipeline-phases.ts",
    topics: `${C}, surface_vegetation_intelligent, phase, every tile, slope gate`,
    provenInProduction: true,
    notes:
      "Phase runs after trails; MUST touch every terrain tile in manifest except vertical-wall-only samples (slope > 42°).",
  },
];
